function [pars_0,lb,ub] = mgOptimBounds(rm_0,var_eta)
        rm_0 = reshape(rm_0,1,2);
        % % % par 9-10: var_et
        var_et_0 = reshape(var_eta,1,2)+1e-3;
        pars_0 = [...
            rm_0,...
            25,...
            25,...
            1,...
            1,...
            0,...
            0,...
            var_et_0,...
            0];
        lb = [...
            0.5*rm_0,...
            1,...
            1,...
            0.01,...
            0.01,...
            0,...
            0,...
            0.1*var_et_0,...
            0];
        ub = [...
            2*rm_0,...
            100,...
            100,...
            Inf,...
            Inf,...
            0,...
            0,...
            10*var_et_0,...
            0];
end
