function [pars_0,lb_pars,ub_pars] =rogOptimBounds(rm_0,var_eta)
%% rogOptimBounds Produces the optimization bounds/starting points for the pairwise Ratio of Gaussians parametrized by the contrast response function
    %% Initialize
        % % % par 1:2 Rmax
        % rm_0 = reshape(max(mean(spikes,3,'default','omitnan'),[],2),1,[]);

        rm_0 = reshape(rm_0,1,2);


        % % % par 17-18: var_et
        var_et_0 = reshape(var_eta,1,2)+1e-3;


    %% Set parameters and bounds
    % % % starting point
    pars_0 =...
            [rm_0,... %Rmax
            20,... %eps
            20,... %eps
            1,... %alpha_n1
            1.5,... %beta_n1
            1,...   %alpha_d1
            1.5,... %beta_d1
            1,...   %alpha_n2
            1.5,... %beta_n2
            1,...   %alpha_d2
            1.5,... %beta_d2
            0,...   %rho_n
            0,...   %rho_d
            0,...   %rho_n1d2
            0,...   %rho_n2d1
            var_et_0,... %var_eta
            0];     %rho_etas
    ub_pars = ...
            [2*rm_0,...
            100,...
            100,...
            20,...
            2,...
            20,...
            2,...
            20,...
            2,...
            20,...
            2,...
            0,...
            0,...
            0,...
            0,...
            10*var_et_0,...
            0];
    lb_pars =...
            [0.5*rm_0,...
            1,...
            1,...
            0.01,...
            1,...
            0.01,...
            1,...
            0.01,...
            1,...
            0.01,...
            1,...
            0,...
            0,...
            0,...
            0,...
            0.1*var_et_0,...
            0];
end
